defaults: &defaults
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 25
  database: sluiters_development
  username: <%= ENV['USERNAME'] %>
  password:
  min_messages: warning
  host: localhost

development:
  <<: *defaults

test: &test
  <<: *defaults
  database: sluiters_test

production:
  <<: *defaults
  database: sluiters_prod
